import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { doc, getFirestore, updateDoc } from 'firebase/firestore';
import { getPerformance } from "firebase/performance";
import Header from '../components/header/Header';
import Footer from '../components/footer/Footer';
import Ratings from '../components/ratings/Ratings';
import firebaseApp, { signIn } from '../lib/firebase';

const db = getFirestore(firebaseApp);

if (process.browser) {
  getPerformance(firebaseApp);
}

export default function Home({ posts }) {
  let email: string = '';
  let password: string = '';

  const rateMovie = async (id: string, rating: number) => {
    await updateDoc(doc(db, 'users', 't6aEmLDMWEzR839g5XsP'), {
      ['ratings.' + id]: rating
    });
  };

  const handleEmail = (event) => email = event.target.value;
  const handlePassword = (event) => password = event.target.value;

  const handleSignIn = async () => {
    signIn(email, password);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Five Stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Five Stars
        </h1>

        <div className={styles.grid}>
          {posts.results.map(movie => (
            <div key={movie.id} className={styles.card}>
              <Link href={'/movie/' + movie.id}>
                <h2>{movie.title}</h2>
              </Link>
              <Image loader={tmdbLoader} src={movie.poster_path} alt={movie.title} width={100} height={148} />
              <div>
                <Ratings movie={movie} />
              </div>
            </div>
          ))}
        </div>
      </main>

      <section>
        <input type="email" onChange={handleEmail} placeholder="email" />
        <input type="password" onChange={handlePassword} placeholder="password" />
        <button onClick={handleSignIn}>Sign in</button>
      </section>

      <Footer />
    </div>
  )
}

export async function getStaticProps({ preview = null }) {
  const res = await fetch('https://api.themoviedb.org/3/discover/movie?api_key=' + process.env.NEXT_PUBLIC_MOVIEDB_API_KEY);
  const posts = await res.json();
  return {
    props: { posts, preview },
  }
}

const tmdbLoader = ({ src, width, quality }) => {
  return `https://image.tmdb.org/t/p/w500/${src}?w=${width}&q=${quality || 75}`
}
